-- Execute this script in your Supabase SQL Editor to update the database schema

-- 1. Create Groups table
CREATE TABLE IF NOT EXISTS groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  responsible TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insert default groups
INSERT INTO groups (name, responsible)
SELECT 'Grupo A', 'Responsable A'
WHERE NOT EXISTS (SELECT 1 FROM groups);

INSERT INTO groups (name, responsible)
SELECT 'Grupo B', 'Responsable B'
WHERE NOT EXISTS (SELECT 1 FROM groups WHERE name = 'Grupo B');

-- 3. Update Invoices table
-- Note: Using double quotes for "Invoices" as it is accessed as such in Dart code
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS group_id BIGINT REFERENCES groups(id);
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS responsible TEXT;
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pendiente';
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS end_date DATE;

-- 4. Ensure we have a way to get Catalog Items (PoleBarns is likely the one)
-- No changes needed if we use PoleBarns table as Catalog.

